"""empty message

Revision ID: 7dd5ad7d8497
Revises: b6f67470beff
Create Date: 2025-01-16 17:53:26.129804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd5ad7d8497'
down_revision = 'b6f67470beff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_document_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'documents', ['documents_id'], ['id'])
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_document_id_fkey', 'documents', ['document_id'], ['id'])
        batch_op.drop_column('documents_id')

    # ### end Alembic commands ###
